name: Publish nuget
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  publish_nuget:
    name: Publish nuget
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: cachix/install-nix-action@v27
      - name: Publish nuget package
        run: nix run .#ci_publish
